### ISSUE TITLE
how do i get keyauth connected to my code 

### ISSUE THREAD

**Issue by VyrexServices** [KeyAuth/KeyAuth-Python-Example#31]
Can somebody help me get keyauth in my code lol im to dumb for that

**Comment by mazk5145** [comment]
Just build example first then remove ```https://github.com/KeyAuth/KeyAuth-Python-Example/blob/86d73b69991e59e0ecdda6ea8e3063876b7cd575/main.py#L81-L82``` these two and then add your code now.
