### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by temal32** [KeyAuth/KeyAuth-Python-Example#46]
C:\Users\Temal\Desktop\KeyAuth-Python-Example-main>main.py
Traceback (most recent call last):
  File "C:\Users\Temal\Desktop\KeyAuth-Python-Example-main\main.py", line 1, in <module>
    from keyauth import api
  File "C:\Users\Temal\Desktop\KeyAuth-Python-Example-main\keyauth.py", line 505
    username = ip = hwid = expires = createdate = lastlogin = subscription = subscriptions ""
                                                                                           ^^
SyntaxError: invalid syntax
![image](https://user-images.githubusercontent.com/76877604/183698572-251c4630-5d7b-4c9f-a50e-37bdd62a4c6a.png)

**Comment by 6nz** [comment]
You probably changed something

**Comment by 6nz** [comment]
That you shouldnt change

**Comment by temal32** [comment]
> That you shouldnt change

No, I didn't. Could you download it and check?

**Comment by sfx2me** [comment]
> That you shouldnt change

Lmao bro, its borken get it, there is a missing = 

but your brain is too small to check it ¯\_(ツ)_/¯

**Comment by sfx2me** [comment]
and even the fixed version with no errors still doesnt work, what is this? super secure? or super bad? and not tested after publishing?

**Comment by imuuid** [comment]
add the "="

**Comment by sfx2me** [comment]
ik but it still doesnt work, i get the error:
This program hash does not match, make sure you're using latest version

**Comment by 6nz** [comment]
Then learn how to use it

**Comment by sfx2me** [comment]
its not my fault lol

**Comment by sfx2me** [comment]
does it work for you?

**Comment by 6nz** [comment]
Works totally fine

**Comment by Pranavprana** [comment]
just change this        
 username = ip = hwid = expires = createdate = lastlogin = subscription = subscriptions = ""
"" is on another line

**Comment by wnelson03** [comment]
@sfx2me you can disable hash check on dashboard.

![image](https://user-images.githubusercontent.com/83034852/185238319-facb8fe7-cacb-4f58-95a1-6dbb94c9e600.png)

sorry about the syntax error, fixed in b91d2a2567d3ca2978041f69bb503f16aa803771
