### ISSUE TITLE
This program hash does not match, make sure you're using latest version

### ISSUE THREAD

**Issue by sfx2me** [KeyAuth/KeyAuth-Python-Example#48]
I got this error as i started the file.

I just downloaded the code, replaced my info and started main.py.

**Comment by 6nz** [comment]
Disable hash check 🤦

**Comment by sfx2me** [comment]
and how?

**Comment by 6nz** [comment]
check application settings or remove it from the code

**Comment by 6nz** [comment]
🤷

**Comment by wnelson03** [comment]
https://keyauth.cc/app/?page=app-settings

![image](https://user-images.githubusercontent.com/83034852/185811994-1e4800d8-0f15-46ac-9f4e-75c85fd7a937.png)
