### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by N0edL** [KeyAuth/KeyAuth-Python-Example#51]
![image](https://user-images.githubusercontent.com/88205753/189549864-d696d8d0-57d7-4dbb-ae50-19917d167c98.png)

i get this on my screen dont now what it meens

**Comment by 6nz** [comment]
Are you using the latest example?

**Comment by 6nz** [comment]
Do you have any HTTP Debugger or VPN enabled?

**Comment by N0edL** [comment]
yes 


HTTP NO
VPN NO

**Comment by wnelson03** [comment]
@N0edL go to https://keyauth.win/api/1.0/

![image](https://user-images.githubusercontent.com/83034852/189799264-ac9e6593-084e-4a80-b68b-9d2c8e11e6d7.png)

Should look like this. Does it look the same? If not please send a screenshot
