### ISSUE TITLE
Not Work On Windows VPS

### ISSUE THREAD

**Issue by emonahmmed** [KeyAuth/KeyAuth-Python-Example#52]
**KeyAuth not work on Windows RDP. My Application credential is correct. But same code perfectly work on Local computer.**

![Error](https://user-images.githubusercontent.com/101325333/191775570-59a10997-4126-4366-9fdd-05e3652fe828.PNG)

**Showing this error**

**Comment by 6nz** [comment]
Did you change anything in the example

**Comment by 6nz** [comment]
Marci#4399

**Comment by 6nz** [comment]
@emonahmmed

**Comment by 6nz** [comment]
So u dont want to DM?

**Comment by 6nz** [comment]
Marci#4399

**Comment by 6nz** [comment]
ID: 968943064662028298

**Comment by 6nz** [comment]
No answers.
