### ISSUE TITLE
I have a questuin , where me need past code to donwload files cuzz i dont know where paste he and he not work

### ISSUE THREAD

**Issue by Ploo0** [KeyAuth/KeyAuth-Python-Example#53]

**Comment by 6nz** [comment]
![image](https://user-images.githubusercontent.com/74118308/197364819-02aa566a-fa74-4824-b5a2-eacda32c9451.png)

**Comment by 6nz** [comment]
If you have any issues or need code help dm me or visit the coding channel
Channel: https://discord.com/channels/824397012685291520/1023005585953787914
Discord: Marci#1337
