### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bl4nkoo** [KeyAuth/KeyAuth-Python-Example#54]
, line 52, in <module>
    keyauthapp = api(
TypeError: 'module' object is not callableallable

**Comment by wnelson03** [comment]
![image](https://user-images.githubusercontent.com/83034852/200789657-f566b40b-a59c-4841-9729-0335953522b9.png)

working for me, other people haven't reported any issues lately either.

try watching this video please https://www.youtube.com/watch?v=L2eAQOmuUiA

also, make sure you're using the default example and not adding the code to your program 

we do not provide support for adding KeyAuth to your project. If you can't figure this out you should use Google or YouTube

**Comment by 6nz** [comment]
^^

**Comment by 6nz** [comment]
> , line 52, in keyauthapp = api( TypeError: 'module' object is not callableallable

you removed a function or added some broken code to the example
